apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-app
  namespace: secureflow

spec:
  replicas: 1

  selector:
    matchLabels:
      app: todo-app

  template:
    metadata:
      labels:
        app: todo-app

    spec:
      containers:
      - name: todo-app
        image: anwayalamwar/todo_app_sunbeam-web

        ports:
        - containerPort: 80

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: DB_HOST

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: DB_USER

        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASS
